# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Empty', 'Empty'), ('GPS', 'GPS'), ('WIFI', 'WIFI')], default='Empty', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GPSCoordinate',
            fields=[
                ('coordinate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='location.Coordinate')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('radius', models.DecimalField(decimal_places=5, max_digits=30)),
            ],
            bases=('location.coordinate',),
        ),
        migrations.CreateModel(
            name='WIFICoordinate',
            fields=[
                ('coordinate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='location.Coordinate')),
            ],
            bases=('location.coordinate',),
        ),
        migrations.AddField(
            model_name='ssid',
            name='coordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Coordinate'),
        ),
        migrations.AddField(
            model_name='location',
            name='coordinate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='location.Coordinate'),
        ),
    ]
