# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='info',
            unique_together=set([('user', 'key')]),
        ),
    ]
